org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod Properties
maven_group=com.example
archives_base_name=addon-template
# Khai báo phiên bản của mod
mod_version=1.0.0

# Nếu dự án là một template, có thể nó cũng sẽ cần thêm các biến cơ bản sau (nếu chưa có):
maven_group=com.yourname.addonautomine
archives_base_name=addonautomine
